# this would only get read in to the distributor

[run_settings]
submission_iteration=1

[ecmwf] 
nnodes = 1 # or 2 or 8...
> still needed? taskfactor = 1 #1 if 1 node, otherwise 3-5, doesn't work yet

walltime="48:00:00"   # (hms) walltime of the job 
cooldown="00:00:30"   # (hms) how long prior end should focus shift to completing running jobs?
hostname="cca"
relaunch="yes"        # with "no", no new iteration will be launched

account_no="spnlberg"
jobname_base="FDM_${project_name}_i"
FDMs_per_node=128 #128 # play around for the optimal performance 
EC_hyperthreads=1
memory_per_task="999Mb"
EC_ecfs=0      # number of parallel ECFS calls 

QUESTIONS: 

> how to import things like `pwd` and $USER?
# other FDM input
export usern=$USER
export homedir=`pwd`

what to do to create a working directory?
  # -------- start of the launching procedure -------
  echo "Start cleaning working directory"
  # prepare launch
  mkdir -p $workdir
#  rm -rf $workdir/*
  mkdir -p $nplogdir
  mkdir -p $workexe
  mkdir -p $requestdir
  mkdir -p $readydir_base
  mkdir -p $p2ms
  mkdir -p $outputdir
  mkdir -p $restartdir
  mkdir -p $p2logs

  cp "$p2exe/$FDM_executable" "$workexe/$FDM_executable"

  if [[ ! -r $gridpointlist ]]; then
    echo "The grid point list is missing!"
    exit 1
  fi  
  cp $gridpointlist ${workpointlist}.txt
    
  let "ncpu_tot=$nnodes_max*$tasks_per_node"
  echo "Run at max on $tasks_per_node cores on $nnodes_max node(s)."  
  echo "So max parallel jobs is ${ncpu_tot}."