##################
# Model settings #
##################

[general_settings]
run_location = "ecmwf" #ecmwf - run on ecmwf; offline - run on home computer; add other options as necessary; used for compiling in launch_job.sc
restart_type = "none" # none -> do spinup; spinup -> start post-spinup; run -> start from end of last run
save_output = 10 # save output every 10 years
nyears_spinup = 30

domain = "FGRN055" # domain name, used in naming conventions #TODO: HERE or in paths??
forcing = "era055" # forcing name, used in naming conventions #TODO: HERE or in paths??

ImpExp = 1 #Impicit or Explicit schemes (1=Implicit/fast, 2= Explicit/slow)
dtmodelExp = 180 #timestep in model with explicit T-scheme [s]
dtmodelImp = 900 #timestep in model with implicit T-scheme [s]
dtSnow = 31557600 #duration of running average of variables used in snow parameterisation [s]

dzmax = 0.15 #vertical model resolution [m]


[model_physics]
DO_MO_FIT = true # if true, use MO=1.0 in firn physics; if false, use domain-dependent MO fits
initdepth = 1.0 #initial depth of firn profile [m]
th = 0.5 #theta (if theta=0.5 , it is a Crank Nicolson scheme)
startasice=1 #indicates the initial rho-profile (1=linear, 2=ice)
begintT=3 #indicates the inital T-profile (0=winter, 1=summer, 2=linear)
NoR = 6 #number of times the data series is repeated for the initial rho profile is constructed

[output_dimensions]
writeinspeed = 86400 #frequency of writing speed components to file
writeinprof = 2592000 #frequency of writing of firn profiles to file
writeindetail = 864000 #frequency of writing of detailed firn profiles to file (10 day resolution)
proflayers = 3000
detlayers = 500
detthick = 0.04

[minimum_values]
ts_minimum = 1.0e-04     #minimum magnitude for timeseries value, set when ts are loaded
det2d_minimum = 1.0e-05 #minimum magnitude for refreezing sum in 2ddetail output


# TKTKTK: all below should be set by netcdf

# [forcing_description] 
# start_ts_year = "1939"
# end_ts_year = "2023" 
# start_ave_year = "1940"
# end_ave_year = "1970"

# # [grid_dimensions]
# numLons = 438
# numLats = 566
# num_longitude_bands = 6
# numTimes = 246424
# nyears_simulation = 84
# dtobs = 10800